add main layout
anna9394/homeWork3 pull request #3
Opened 2020-12-08 09:36 UTC by anna9394

2020-12-08 15:43 UTC, aviktius requested changes

2020-12-08 15:43 UTC, aviktius commented on index.html
> +                <a class="contact-logo">Follow Us on Twitter</a>
у ссылки должен быть атрибут href

2020-12-08 15:43 UTC, aviktius commented on index.html
> +            <div class="btn">
название класса должно быть во множественном числе (содержит несколько кнопок)

2020-12-08 15:43 UTC, aviktius commented on index.html
>          <ul class="header-menu">
добавить семантический тег nav

2020-12-08 15:43 UTC, aviktius commented on styles.css
> +  vertical-align: middle;
это свойство точно нужно?

2020-12-08 15:43 UTC, aviktius commented on styles.css
> +  margin-left: 380px;
если ширина макета изменится, придется менять margin. Отступ должен быть динамический (margin-left: auto)

2020-12-08 15:43 UTC, aviktius commented on styles.css
> +.btn button {
кнопкам как и ссылкам нужны псевдосостояния

2020-12-08 15:43 UTC, aviktius commented on styles.css
> +  vertical-align: middle;
это свойство точно нужно?

2020-12-08 15:43 UTC, aviktius commented on styles.css
> +  margin-left: 120px;
если нам нужно сместить элемент вправо или влево в крайнюю точку, то мы не подбираем четкое цифровое значение. Нужно выравнивать через text-align или margin: auto. (ссылка по умолчанию inline-элемент)

2020-12-08 15:43 UTC, aviktius commented on styles.css
> +  list-style: none;
это можно обнулить глобально

2020-12-08 15:43 UTC, aviktius commented on index.html
> +                <img src="img/design.png">
alt атрибут

2020-12-08 15:57 UTC, aviktius requested changes

2020-12-08 15:57 UTC, aviktius commented on index.html
> +        <a href="#" class="header-logo">Wood Design</a>
при наведении выделяется логотип

2020-12-08 15:57 UTC, aviktius commented on index.html
> +            <div class="card">
карточки скорее всего будут кликабельные, поэтому нужно обернуть их в ссылку

2020-12-08 15:57 UTC, aviktius commented on styles.css
> +.btn button {
всем интерактивным элементам стоит задавать при наведении cursor: pointer

2020-12-09 10:46 UTC, anna9394 commented on styles.css
> +  padding: 5px 15px;
у меня не получилось исправить при добавление paddinga для ссылок

2020-12-09 11:21 UTC, anna9394 commented on styles.css
> +  margin-left: 120px;
это не получилось

2020-12-10 14:31 UTC, merged